- name: install nginx server  
  ansible.builtin.dnf:
    name: nginx 
    state: installed

- name: start and enable nginx
  ansible.builtin.service: 
    name: nginx
    state: started
    enabled: yes

- name: delete exist html irectory
  ansible.builtin.file:
    state: absent 
    path: /usr/share/nginx/html

- name: create html directory
  ansible.builtin.file:
    state: directory
    path: /usr/share/nginx/html

- name: download the app code in tmp folder
  ansible.builtin.get_url:
    url:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: unzip the application code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: true

- name: copy the conf file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - restart nginx

